### ISSUE TITLE
If tags are camelCase, missingJSONKeys will fail

### ISSUE THREAD

**Issue by Jarema** [clbanning/checkjson#1]
Hi!

In current implementation if you will set tag to be camelCase, it will break the validation saying it is missing the camelCased key.

### How to reproduce

in TestJSONKeysWithTags change

```data := []byte(`{"ok":true,"whynot":"it's a test"}`)```

to:

```data := []byte(`{"ok":true,"whyNot":"it's a test"}`)```

of course also change the struct definition.

Im happy to contribute. Im guessing that strings.ToLower is a culprit of that issue, though it occurs so many times in codebase its hard to easily pinpoint exact place.

Could you target me to proper place to help with it?

Best

**Comment by clbanning** [comment]
Yup.  When grabbing the json tag to override the struct member label, the tags[0] value is not coerced ToLower like the json keys and struct member labels.  See: https://github.com/clbanning/checkjson/blob/master/missingkeys.go#L162.

The same issue exists in  existingkeys.go (line 134) and unknownkeys.go (line 116). 

Need camelCase test cases added, as well.

Have at it.

**Comment by clbanning** [comment]
Note: the encoding/json package essentially does the same thing and will decode a camelCase key:value pair `"whyNot":"this is a test"` into a struct member with the tag `json:"whynot"` or a non-tagged struct member `Whynot string`.  

Since this package is intended to check JSON objects that will be decoded using encoding/json, it should exhibit similar behavior.

**Comment by clbanning** [comment]
Handled by release v1.4.
